version: '3.7'

services:
  mysql:
    container_name: 'adm-videos-mysql'
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - adm-videos-network

networks:
  adm-videos-network: 


