name: CI Pipeline

on:
  push:
  #Interface manualmente
  workflow_dispatch:

jobs:
  # Job para a execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração de passos do nosso jog
    steps:
      # Checkout do código fonte
      - uses: actions/checkout@v3
      # Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # Configurar a JDK na máquina
      - name: Run application tests
        run: |
          chmod +x ./gradlew
          ./gradlew test
         



